[2025-08-17T15:43:11.015+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T15:43:11.071+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: excel_to_mysql_daily_7am.ensure_table scheduled__2025-08-16T00:00:00+00:00 [queued]>
[2025-08-17T15:43:11.081+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: excel_to_mysql_daily_7am.ensure_table scheduled__2025-08-16T00:00:00+00:00 [queued]>
[2025-08-17T15:43:11.082+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-17T15:43:11.095+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): ensure_table> on 2025-08-16 00:00:00+00:00
[2025-08-17T15:43:11.109+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'excel_to_mysql_daily_7am', 'ensure_table', 'scheduled__2025-08-16T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_mysql_dag.py', '--cfg-path', '/tmp/tmpnztk6f8x']
[2025-08-17T15:43:11.118+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask ensure_table
[2025-08-17T15:43:11.120+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-17T15:43:11.121+0000] {standard_task_runner.py:63} INFO - Started process 199 to run task
[2025-08-17T15:43:11.296+0000] {task_command.py:426} INFO - Running <TaskInstance: excel_to_mysql_daily_7am.ensure_table scheduled__2025-08-16T00:00:00+00:00 [running]> on host 76f8879dcf2c
[2025-08-17T15:43:12.173+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='excel_to_mysql_daily_7am' AIRFLOW_CTX_TASK_ID='ensure_table' AIRFLOW_CTX_EXECUTION_DATE='2025-08-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-16T00:00:00+00:00'
[2025-08-17T15:43:12.174+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T15:43:12.175+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS excel_combined (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  source_sheet VARCHAR(128),
  load_date DATE,
  col1 TEXT NULL,
  col2 TEXT NULL,
  col3 TEXT NULL,
  col4 TEXT NULL,
  col5 TEXT NULL,
  col6 TEXT NULL,
  col7 TEXT NULL,
  col8 TEXT NULL,
  col9 TEXT NULL,
  col10 TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
[2025-08-17T15:43:12.187+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T15:43:12.201+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_target` isn't defined
[2025-08-17T15:43:12.209+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=excel_to_mysql_daily_7am, task_id=ensure_table, run_id=scheduled__2025-08-16T00:00:00+00:00, execution_date=20250816T000000, start_date=20250817T154311, end_date=20250817T154312
[2025-08-17T15:43:12.223+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task ensure_table (The conn_id `mysql_target` isn't defined; 199)
[2025-08-17T15:43:12.260+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-17T15:43:12.305+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-08-17T15:43:12.322+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-17T15:43:12.326+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
