[2025-08-16T08:40:35.545+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-16T08:40:35.597+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: excel_to_mysql_daily_7am.ensure_table scheduled__2025-08-15T00:00:00+00:00 [queued]>
[2025-08-16T08:40:35.607+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: excel_to_mysql_daily_7am.ensure_table scheduled__2025-08-15T00:00:00+00:00 [queued]>
[2025-08-16T08:40:35.608+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-16T08:40:35.629+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): ensure_table> on 2025-08-15 00:00:00+00:00
[2025-08-16T08:40:35.656+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'excel_to_mysql_daily_7am', 'ensure_table', 'scheduled__2025-08-15T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_mysql_dag.py', '--cfg-path', '/tmp/tmpxqb7trpy']
[2025-08-16T08:40:35.660+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask ensure_table
[2025-08-16T08:40:35.663+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=185) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-16T08:40:35.665+0000] {standard_task_runner.py:63} INFO - Started process 198 to run task
[2025-08-16T08:40:35.803+0000] {task_command.py:426} INFO - Running <TaskInstance: excel_to_mysql_daily_7am.ensure_table scheduled__2025-08-15T00:00:00+00:00 [running]> on host 4973bafe0a32
[2025-08-16T08:40:36.007+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='excel_to_mysql_daily_7am' AIRFLOW_CTX_TASK_ID='ensure_table' AIRFLOW_CTX_EXECUTION_DATE='2025-08-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-15T00:00:00+00:00'
[2025-08-16T08:40:36.008+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-16T08:40:36.009+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS excel_combined (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  source_sheet VARCHAR(128),
  load_date DATE,
  col1 TEXT NULL,
  col2 TEXT NULL,
  col3 TEXT NULL,
  col4 TEXT NULL,
  col5 TEXT NULL,
  col6 TEXT NULL,
  col7 TEXT NULL,
  col8 TEXT NULL,
  col9 TEXT NULL,
  col10 TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
[2025-08-16T08:40:36.032+0000] {base.py:84} INFO - Using connection ID 'mysql_target' for task execution.
[2025-08-16T08:40:36.051+0000] {base.py:84} INFO - Using connection ID 'mysql_target' for task execution.
[2025-08-16T08:41:13.719+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-16T08:41:13.726+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown server host 'mysql' (-3)")
[2025-08-16T08:41:13.770+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=excel_to_mysql_daily_7am, task_id=ensure_table, run_id=scheduled__2025-08-15T00:00:00+00:00, execution_date=20250815T000000, start_date=20250816T084035, end_date=20250816T084113
[2025-08-16T08:41:13.807+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task ensure_table ((2005, "Unknown server host 'mysql' (-3)"); 198)
[2025-08-16T08:41:13.840+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-16T08:41:13.868+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-08-16T08:41:13.889+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-16T08:41:13.894+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
